---
title: "p8105_hw5_cs3779"
author: "CJ Snyder"
date: "11/7/2019"
output: github_document
---

```{r}
library(tidyverse)
library(knitr)
library(readxl)
library(viridis)
library(patchwork)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# **Problem 1**
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

kable(iris_with_missing)

replace_missing = function(x) {
  if (is.numeric(x)) {
    x = round(replace_na(x, mean(x, na.rm = TRUE)), digits = 1)
  }
  else if (is.character(x)) {
    (x = replace_na(x, "virginica"))
  }
}

output = vector("list", length = 5)

for (i in 1:5) {
  output[[i]] = replace_missing(iris_with_missing[[i]])
}

iris_with_missing = map_df(.x = iris_with_missing, ~replace_missing(.x))

kable(iris_with_missing)
```


# **Problem 2**
```{r}
prob2_df = list.files(path = "./data", pattern = "*.csv", full.names = T) %>% 
    map_dfr(~read.csv(.)) %>% 
  mutate(
    treatment_arm = list.files(path="./data") %>% 
              word(sep="_")
  ) %>% 
  rownames_to_column(var = "subject_id") %>%
  mutate(
    treatment_arm = str_replace(treatment_arm, "con", "control"),
    treatment_arm = str_replace(treatment_arm, "exp", "treatment")
  ) %>% 
  select(subject_id, treatment_arm, week_1:week_8) %>%
  pivot_longer(
    cols = starts_with("week"),
    names_to = "week"
  )

prob2_plot = 
  ggplot(prob2_df, aes(x=week, y=value, group=subject_id, color=treatment_arm)) +
  geom_point() + geom_line()

prob2_plot
```

**Notes:** Comparing the treatment arm to the control arm, it seems that by the end of the 8 week observation period that the treatment arm had on average higher values than the control arm. Additionally, both groups started with around the same values, but began separating after the second week of observation.

# **Problem 3**
```{r}

```












